### ISSUE TITLE
Return event object when onFocus.

### ISSUE THREAD

**Issue by damianprzygodzki** [YouCanBookMe/react-datetime#118]
I think it is really important to get the event object when implementing own onFocus callback. I can't imagine any onFocus implementation without reference to what exactly happened. Creating refs to each DateTime component is not nice.

**Comment by arqex** [comment]
Maybe the `onFocus` and `onBlur` names for the react-datetime's props are not well chosen. They should be named `onOpen` and on `onClose` because that is what they really are.

If you need to use a real `onFocus` handler for the input you can add it to `inputProps`, that way you will get access to your `event` object.
