### ISSUE TITLE
Cannot read property 'standalone' of undefined, when using moment 2.14.x

### ISSUE THREAD

**Issue by pruik** [YouCanBookMe/react-datetime#119]
When using moment 2.14.1 and the DateTime component with a dutch locale (nl), clicking on the month makes the entire component freeze and the console pops up this error:

`Cannot read property 'standalone' of undefined`

It seems like the component is trying to access '_monthsShort' in the date's localeData (in MonthsView.js:59), but this array was removed in the latest version of Moment. 

I can use Moment 2.13 for now, but I just thought I should point this out.

**Comment by arqex** [comment]
Thanks @pruik 

The component uses that array because it's the fastest way of having all the shortnames for the months. But it has been a source of problems from the very begining, because it exists (or not) depending on the locale used.

We probably would need to get all the names using moment js method, and cache them internally for the current locale to stop seeing this kind of problems.

**Comment by fruitl00p** [comment]
@arqex after alot of hairpulling a possible fix might be always falling back to the `moment.monthsShort()`-method of moment itself.

**Comment by simeg** [comment]
@pruik @fruitl00p this is fixed in version 2.7.2 which I just released.
