### ISSUE TITLE
react-boostrap-datetimepicker redirect to you

### ISSUE THREAD

**Issue by chollier** [YouCanBookMe/react-datetime#122]
Hey @YouCanBookMe,

Just a head-up that I deprecated https://github.com/quri/react-bootstrap-datetimepicker (see README), as well as the npm package (message redirects to your repo).

**Comment by arqex** [comment]
Oh, that's a pity. It's been a while since I decided to clone your repo, it was the best datepicker I could find for react then. I especially loved the way you structured the views and the simple communication with the main component. The only thing that didn't fit to me was the boostrap part :)

I also found myself in a positon that I couldn't maintain this datepicker, (maintaining it is a lot of work and not much grateful) but fortunatelly YouCanBookMe could host the project and now I can spend some hours a week to keep it in fit.

Good luck with your next projects and thanks!

**Comment by davidfurlong** [comment]
This repo seems to be unmaintained (lots of open PRs that haven't been merged and look good and have been waiting for 30 days)

**Comment by arqex** [comment]
Sorry @davidfurlong for the delay, I am on holidays and I am the only maintainer. From all the open PRs open only the latest 2 are considered to be merged, in case you need to know the direction that the datepicker is going.

**Comment by davidfurlong** [comment]
@arqex ah okay, sorry I didn't mean to jump to any conclusions. I'm particularly interested in updating to newer versions (15) of React

**Comment by simeg** [comment]
@davidfurlong I've been added as a maintainer to this repo so hopefully things will move a bit quicker now. I'll take into consideration your idea about updating this to comply better with v.15 of React and looking forward to your future ideas.

**Comment by jmfrancois** [comment]
So this issue should be closed ?
