### ISSUE TITLE
Changing Locale does not immediately change component.

### ISSUE THREAD

**Issue by layneanderson** [YouCanBookMe/react-datetime#126]
I dynamically change the Locale (e.g. locale={theLocale} ) and it does not change the language on the component right away.  It does change after I select a date and then reopen the date-picker.

**Comment by arqex** [comment]
Hey @layneanderson 

Thanks for contacting, that's because the locale is set when the moment.js object that the datepicker uses internally is updated, so the current moment.js object is not being affected by the change and we need to refresh it somehow.

We probably should check the change at `componentWillReceiveProps` and refresh the internal moment.js to make it work as expected.

**Comment by layneanderson** [comment]
Hi @arqex 

I thought this was the case.  I've run into similar issues on my own components and fixed it in `componentWillReceiveProps` as well.  I was curious to see if there was another way to fix that I haven't thought of. :smile: 

You guys are doing a great job, thanks!

**Comment by arqex** [comment]
It's the simplest fix, isn't it? Duplicating the data that a component rely on is always a source of issues, react-datetime does it in several places, that we hope we can fix it in the future.

In the case of the `locale` prop, the `componentWillReceiveProps` I think it's the only solution, because that part of the state lives in the moment.js object. For other props, maybe there are other solutions.

I have a particular point of view on how to handle APIs for react components, and not much people agree with me:

https://medium.com/@arqex/non-functional-react-js-6e020ce27ee2

This doesn't mean that this component will follow what the post says, but I have seen that approach more and more frequently in react-native components, so maybe it's something interesting to think about.

**Comment by simeg** [comment]
Fixed in #254 (changes merged in #266).
