### ISSUE TITLE
IsValidDate Not hire when dateFormat is set

### ISSUE THREAD

**Issue by katzuta** [YouCanBookMe/react-datetime#129]
Hi,
The function IsValidDate is not hire when we set a dateFormat
example : http://codepen.io/anon/pen/dpyEGr?editors=1112

In the example, we want limit month selector, without this function we can't...

**Comment by simeg** [comment]
Hi @katzuta,

I agree, you should be able to use a `dateFormat` and `isValidDate` at the same time. I'll see what I can find 🔬. Feel free to look at it yourself as well, if you'd like.

**Comment by simeg** [comment]
Hey, it turns out there was a PR fixing this that was not merged. I merged it and bumped the version, so when the creator of this package (who has access to the npm repo) publishes it to npm then you can download it it. It shouldn't take more than a day or two for him to do that. 

I'll close this for now and if you're still having problems with 2.7.0 feel free to open it.
