### ISSUE TITLE
Time zone support?

### ISSUE THREAD

**Issue by MilosRasic** [YouCanBookMe/react-datetime#137]
Does this component support time zone for the displayed time? For example, if I set defaultValue as string or Date object or moment object that contains time zone information with time zone other than the user's local setting, will this be displayed in the datetimepicker or will it be converted to user's local time zone?

**Comment by simeg** [comment]
Hi @MilosRasic,

As the API specifies, you can use a moment.js date to set the `defaultValue`, and you can specify a specific timezone for the moment.js date. [Here you can read more about timezones and moment.js](http://momentjs.com/timezone/). I hope this answers your question, otherwise let me know.

**Comment by simeg** [comment]
@MilosRasic are you still having problems?

**Comment by holyman2k** [comment]
if the date picker need to be empty initially, how can I set the timezone?

**Comment by aarchsk** [comment]
Can you please let me know how can i set the timezone.
