### ISSUE TITLE
Click outside doesn't close calendar

### ISSUE THREAD

**Issue by greenais** [YouCanBookMe/react-datetime#169]
Clicking outside doesn't close calendar and time-picker (if they were opened) - where could be an issue?
And if I put two <Datetime> components on the one page (even inside separate divs) - only first one works, second doesn't respond at all. What could be wrong?

On top of this:
I'm on react 15.3.2 and getting 13 warnings in console (for different props) like this:
_> Warning: You are manually calling a React.PropTypes validation function for the `onFocus` prop on `Constructor`. This is deprecated and will not work in the next major version. You may be seeing this warning due to a third-party PropTypes library. See https://fb.me/react-warning-dont-call-proptypes for details._

**Comment by simeg** [comment]
Hi @greenais. About when clicking outside - have you by any chance set the prop `disableOnClickOutside` to `true`? Because in that case it's not suppose to close if you click outside of the component.

This component is not tested using `react` v15 yet, it's something we have on the roadmap to be done. I have stumbled upon the error you are getting for this component before, in that case the versions of the dependencies was the cause (don't know if it was specifically React, but probably). **I think this might be the root of all the problems you are having.** There might be some valuable information in issue #112 though.

If you'd like to create a PR for `react-datetime` supporting `react` v15 I'd happy to review it! Hope this reply was of any help :)

**Comment by greenais** [comment]
Hi @simeg,
no, I didn't set anything special. just plain <Datetime/>. Even more - tried closeOnSelect={true} which doesn't work either.
Thank you for your response, I've doublechecked #112 to get some clue but with no good, unfortunately.
Sorry, I'm not that familiar with GH pool requests yet, could you please guide me in some right direction? I'd like to help contribute to your great work, really.

**Comment by simeg** [comment]
Could you try removing one component to see if you're still having problems with the click outside, please? 

Sure, help is always appreciated! Here's some info about [creating your first pull request](http://www.davepaquette.com/archive/2016/01/24/Submitting-Your-First-Pull-request.aspx), you should also read the [`CONTRIBUTING.md`](https://github.com/YouCanBookMe/react-datetime/blob/master/CONTRIBUTING.md) for specific contribution "rules" for this repo. Looking forward to your pull request!

**Comment by greenais** [comment]
Thank you for the help - the issue was related to the mess with Webpack, sorted out.
Sorry for disturbing(
Datetime works great, awesome work, thank you!
Closed.
