### ISSUE TITLE
isValidDate should apply months and years views

### ISSUE THREAD

**Issue by GilmarLira** [YouCanBookMe/react-datetime#175]
Hello,

We are migrating from our old date picker, to this, fancy, React one. I just implemented the `isValidDate` prop successfully, and although working great on the Days view, it leaves both Months and Years unattended.

Insights on your future additions, or suggestions as how I could implement this functionality, would be appreciated.

Desired outcome:
![screen shot 2016-10-26 at 11 30 51 am](https://cloud.githubusercontent.com/assets/4925585/19739773/25c8d3c6-9b71-11e6-8b69-bc6f65819070.png)

**Comment by simeg** [comment]
Hi @GilmarLira.

This is a good idea and we've been talking about including it in the V3 which we will begin working on soon. If you want to you can create a PR for this and I'll review it, otherwise I'll ask you to wait for V3 :) Thanks.

**Comment by simeg** [comment]
Hey, it turns out there was a PR fixing this that was not merged. I merged it and bumped the version, so when the creator of this package (who has access to the npm repo) publishes it to npm then you can download it it. It shouldn't take more than a day or two for him to do that. 

I'll close this for now and if you're still having problems with 2.7.0 feel free to open it.

**Comment by GilmarLira** [comment]
Fantastic! Thanks!

**Comment by bjbrewster** [comment]
This feature is currently calling `isValidDate` for each day of the year to determine if the year is valid although it stops early when the first valid day is found.  Same for months.  

Should we add isValidMonth and isValidYear options to allow users to provide a faster test?  At the moment, is most likely used to implement min and max date range.
