### ISSUE TITLE
Typings not compatible with Typescript 2.0

### ISSUE THREAD

**Issue by AaronAsAChimp** [YouCanBookMe/react-datetime#181]
The typings for React have changed with Typescript 2.0. They are now installed through the NPM package '@types/react'. This causes a compilation failure, shown below, because there is no longer a  `__React` namespace.

New typings:
https://github.com/DefinitelyTyped/DefinitelyTyped/blob/types-2.0/react/index.d.ts

Error:
```
TypeScript error: [...]/node_modules/react-datetime/react-datetime.d.ts(8,18): Error TS2503: Cannot find namespace '__React'.
```

**Comment by leth** [comment]
It might be enough just to change `__React` to `React`, can anyone confirm?

**Comment by AaronAsAChimp** [comment]
I think you can just get rid of the whole import statement.

**Comment by simeg** [comment]
I don't work with TypeScript so if someone with more experience than me (and an environment to actually test it in) could take a look at this I'd would be grateful. Thanks.

**Comment by AaronAsAChimp** [comment]
I can submit a pull request with the typings I'm using, If you would find that helpful.

**Comment by leth** [comment]
Perhaps we could also add a typescript example and make it part of the travis build? That would probably help @simeg in the long run.

**Comment by grushetsky** [comment]
@AaronAsAChimp, could you share or submit your typings, please?

**Comment by PeterKottas** [comment]
Hi guys, nice work on this issue, I gave it a go and it fixes the problem for us as well. I was just wondering if you know when this is going out. I have a guy waiting for PR because of the typings bug and not sure if I should just merge it in and create an override for the module somehow or wait if the release is only couple days away. Any info much appreciated, thanks :)

**Comment by PeterKottas** [comment]
Ok fixing it myself in the meantime :) Please let me know when you release this one. Thanks ;)

**Comment by ncphillips** [comment]
I am also awaiting this release!

**Comment by PeterKottas** [comment]
Hi @ncphillips I suggest looking at #215, vissermc's answer, going to implement it myself at the moment as a temp fix.

**Comment by simeg** [comment]
Closing this as #190 was merged and version 2.8.0 was just released.

**Comment by PeterKottas** [comment]
Hi @simeg this still appears to be a problem in the recent release. Seems like you might have forgotten to merge. Typings are still wrong. Take a look at https://github.com/vissermc/react-datetime.git#512bf6f7c3f664b8268de9b3d68e4671feda903c which is working for me. You just need to comment out the line with react basically.

**Comment by AaronAsAChimp** [comment]
@PeterKottas Which version of TypeScript are you using? If you are using 2.0+ it should automatically detect the new typing and use them. If you've previously added a workaround you should remove it.

**Comment by PeterKottas** [comment]
Hi @AaronAsAChimp, we use typescript 2.1. Looking at the code from release https://github.com/YouCanBookMe/react-datetime/releases/tag/v2.7.2 . In package.json there's 
"types": "./react-datetime.d.ts",
Then in that file, you have 
  import React = __React; 
on line 8
That appears to be the problem.
I don't have a workaround, I am basically poitning straigh to  https://github.com/vissermc/react-datetime.git#512bf6f7c3f664b8268de9b3d68e4671feda903c instead of v2.7.2 release of this repo.
Hope that helps. 
I can record my screen for you if you want and show you the actual problem but this should make it clear.

**Comment by AaronAsAChimp** [comment]
@PeterKottas The fix was released in v2.8.0, try updating to the latest version and see if that fixes your issue.

**Comment by PeterKottas** [comment]
Ok starting to make sense. There's no release 2.8.0 on github. The last one here is 2.7.2 which doesn't have the fix in it. I'll check out 2.8.0 via NPM tomorrow at work and will let you know.

**Comment by simeg** [comment]
@PeterKottas Sorry that's my mistake, I incorrectly assumed everyone is using the package via npm. I'll publish a version right now.

**Comment by PeterKottas** [comment]
No worries mate, I am pretty sure it will work now. It was just miscommunication.

**Comment by simeg** [comment]
Version 2.8.2 is now live both on npm and as a release here on GitHub. If you have any problems regarding the TS stuff, report it in this issue. Thanks.

**Comment by stonecold123** [comment]
I put `import * as React from 'react'` at the top of index.d.ts and this error `Error TS2503: Cannot find namespace '__React'` is gone.  

Can anyone solve the error from `export = ReactDatetime;` at the bottom of the script? It is throwing `Error:(167, 3) TS2666:Exports and export assignments are not permitted in module augmentations.`
