### ISSUE TITLE
Format of the input

### ISSUE THREAD

**Issue by sverhagen** [YouCanBookMe/react-datetime#234]
This is a question for now, not an issue (yet). Also, I'm new to React, so I might be overlooking something stupid, here.

I'm using the component as follows:

    <Datetime value={this.props.value} onChange={this.onChange} timeFormat="HH:mm" input={true}/>

I want to represent my dates across my application, internally, as strings in the `moment.format()` representation, i.e.: `"2017-01-18T00:00:00-08:00"`.

I want to show my dates across my application, consistently, in the following format: `"dddd, MMM. Do YYYY, HH:mm (hh:mm a)"`.

So, I would like the input of `Datetime` to show something like this: "`Wednesday, Jan. 18th 2017, 00:00 (12:00 am)`". It seems that the only way to show _that_, is to pass it into the component like _that_ (`value`). But then how can the component parse that properly?

I'm seeing `timeFormat` and `dateFormat` as specifications of how to represent date/times _inside_ the picker, just not how to format the input. Is that a thing?

Thank you.

**Comment by axelboc** [comment]
I'm currently working around this by disabling the built-in input and rendering my own hidden input next to the picker.

**Comment by simeg** [comment]
Hi @sverhagen.

Would this solution work for you?

```
var onChange = function(value) {
  // value is here a valid moment.js object,
  // so you can probably parse it to whatever
  // format you need
  console.log(value);
}

<Datetime dateFormat={"dddd, MMM. Do YYYY, HH:mm (hh:mm a)"} onChange={onChange} />
```

**Comment by axelboc** [comment]
Hmm the problem is that `dateFormat` and `timeFormat` are used to format both:
- the selected date/time displayed to the user and
- the `value` of the `input` element

The easiest solution I can think of would be to keep `dateFormat` and `timeFormat` for the displayed date/time, but add a new prop specifically for the input - e.g. `inputFormat="..."`. Since date and time are combined into the same `input` element, there's no need for separate formats like with the displayed date/time.

**Comment by sverhagen** [comment]
Yes, that seems to be what is necessary. There is a bit of a thing about the name, though: "input" makes it sound like it'll affect how people input the data, which I believe it isn't; it's just named after the `<input/>`. Anyway, it doesn't matter, and I would appreciate an update to this already-awesome component!

**Comment by sverhagen** [comment]
What I maybe didn't appreciate at the time of writing this issue is that the `input` really also allows entry of a date/time, and not just as a display, and a way to open the picker. My complex date/time format (`"dddd, MMM. Do YYYY, HH:mm (hh:mm a)"`) may be a bit too much for that anyway. So, I'm going back to `input={true}`, and that's that :wink:

**Comment by layneanderson** [comment]
I'm not sure I'm following what you are really trying to do or what the issue is but ...

It seems to me that to display in the format you want you would just write
`<Datetime value={this.props.value} onChange={this.onChange} dateFormat="dddd, MMM. Do YYYY, HH:mm" timeFormat="HH:mm (hh:mm a)" />`

Then, since the internal value of DateTime is a MomentJS object, you get the value and format it the way you want in your onChange handler to pass on to other parts of your app.

**Comment by axelboc** [comment]
Unfortunately, this way of getting the value is not always possible. Personally, I work with a legacy code base and have to rely on the browser's default form submission (at least for now), so it's crucial that the `input` is formatted the way the server expects it to be.

**Comment by layneanderson** [comment]
Ahh, I understand now your using this as an [uncontrolled component](https://facebook.github.io/react/docs/forms.html#uncontrolled-components).  Sorry can't offer a suggestion, I've only mixed React components with non-React ones on the output side.

**Comment by axelboc** [comment]
Well, I do control it in order to render my own input, as mentioned in my initial comment, but yes, you're right, if I could customise the format of the input, I wouldn't need to. However, I think this is more of a **progressive enhancement** rather than controlled/uncontrolled issue: it's always good practice to ensure that the front-end works without JS (assuming a server-side rendering set up, of course).

**Comment by dlape** [comment]
plss help me with this one im new in react and we are using the same plugin and i cant get the value of DateTime field and put it to the alert box.. can someone give me some examples? sorry for my noobness. :'(

**Comment by lakshmikarnati** [comment]
how to overridden on change method?
may i know the process or example code
