### ISSUE TITLE
Allow Modification of Input className Property

### ISSUE THREAD

**Issue by abrad45** [YouCanBookMe/react-datetime#255]
### I'm Submitting a ...

```
[ ] Bug report
[x] Feature request
[ ] Support request
```

### Steps to Reproduce

N/A

### Expected Results

The developer should be able to customize the `className` of the input tag.

### Actual Results

Currently, you cannot customize the `className` attribute for the input, even though you can customize other attributes via the `inputProps` property.

Here's the line where you can see the `className` is hard coded to `form-control`: https://github.com/YouCanBookMe/react-datetime/blob/master/DateTime.js#L391

**Comment by simeg** [comment]
Hi @abrad45.

Actually, you _can_ provide a custom `className` to the input element by using `inputProps`. [Here's a demo to prove it](http://codepen.io/simeg/pen/EZRgGw) (inspect the DOM to see it).

The reason why `form-control` is not used when `inputProps` contains a `className` property is because
>Properties in the target object will be overwritten by properties in the sources if they have the same key.  **Later sources' properties will similarly overwrite earlier ones.**
(https://developer.mozilla.org/en/docs/Web/JavaScript/Reference/Global_Objects/Object/assign)

This could've been a potential bug if we were relying on `form-control` to always be attached to the `input` element, but it does not seem like we do. I always appreciate a feature suggestion, even if we already support it :) Thanks.

**Comment by abrad45** [comment]
I'm really glad this is supported! I should have looked through the code a bit better ~~or, you know, tried it out first~~ but setting `className` in `inputProps` should maybe appear in the readme as a possibility?

Thanks for an awesome plugin.

**Comment by simeg** [comment]
>but setting className in inputProps should maybe appear in the readme as a possibility?

Sure, we can add that. Thanks.
