### ISSUE TITLE
Figure out how to handle styling

### ISSUE THREAD

**Issue by simeg** [YouCanBookMe/react-datetime#319]
http://editorconfig.org/

**Comment by layneanderson** [comment]
I find something like this is trying to solve a nitpick problem.  I'm trying to say this in the nicest way possible, so please take no offence (as none is intended).  Unless someone has really butchered a PR, a few minor spaces or line feeds isn't a big deal.  There are far too many hours spent correcting nit issues, when this time could be spent writing or reviewing code.  I also think that PRs should allow maintainers to edit so that nit issues can just be corrected instead of putting it back on the submitter to correct (this adds so much unecessary time to the process).

Have you checked out https://github.com/prettier/prettier ?  It is getting lots of attention from React's core devs and seems like an elegant solution.  (It's on my to-do list to add to my stack)

Cheers,

Layne

**Comment by simeg** [comment]
@layneanderson No offence taken at all, I of course want input from other developers. I generally don't think this is a good approach either, I think the linter should just take care of styling. But in every single PR I see the style being weird, and I don't blame people because I can't seem to figure out what is being used - tabs or spaces or a combination. In my editor everything looks good until it ends up on Github, and then every line is broken. 

Why I don't want to add it to the linter is because then I'd have to update a lot of lines because the code base is not in a consistent state when it comes to styling (I've tried this before). I'm up for testing any tool that will help this but I don't like changing every line because of this :/ So not sure what to do really.

I'll look into that tool, thanks. What do you think about this?

**Comment by simeg** [comment]
Prettier looks nice, I'd like to use it. Running it on the code (excluding config files for webpack and gulp) gives `-1,437 +1,452` though. Since prettier is not very customizable some of the styling choices are lost, like having semi-colon on separate line and spaces like these `function( arg )`.

As I'm not the author of this codebase I don't want to do this without any input from the author. @arqex What do you think?

**Comment by simeg** [comment]
Enough is enough. I'm fed up with the weird formatting this project has. Let's use Prettifier on all source code, what do you say @layneanderson?

**Comment by layneanderson** [comment]
I’m without a computer this week so I won’t be able to review the details but I fully support the idea. 

- Layne
