### ISSUE TITLE
Add icon calendar toggle option

### ISSUE THREAD

**Issue by eduardoinnorway** [YouCanBookMe/react-datetime#321]
I would be really nice if you could choose to toggle the calendar with an icon instead of on focus. The issue with onfocus is that when you have some async action on another input before the calendar you will loose the focus and the calendar will be closed when tabing to it, if you render some data from the async call.

**Comment by gor181** [comment]
I looked around the code a bit, and there seems to be a method which does exactly what you want [here](https://github.com/YouCanBookMe/react-datetime/blob/master/DateTime.js#L347-L353).

So there are actually 2 approaches possible:

1. Set a ref to DateTime and assign it to property on the context such as `this.picker`. Then call `this.picker.openCalendar()`. So when you click on the calendar icon you would just call the method and the calendar would appear.
2. maintain state whether the picker is open or closed and pass `open={true}` or `open={false}`. So when you would click the calendar icon it would set the open state `true`. Then it's just matter of passing the `open` to `DateTime` as `<DateTime open={this.state.open} ... />

**Comment by eduardoinnorway** [comment]
Muchas gracias for answer

**Comment by wasinsandiego** [comment]
For those on a similar quest...

Suggestion #2 is a good way to go but there's one caveat. Using the `open` prop to control the open/closed state works, however it does not disable open/close on focus/blur of the input. Usually the reason for adding a calendar icon is to manually control the date picker using the icon instead of the input.

There is already an open issue on this point.
https://github.com/YouCanBookMe/react-datetime/issues/578
