### ISSUE TITLE
Help! Strict Parsing Does not work

### ISSUE THREAD

**Issue by Andriy-Kulak** [YouCanBookMe/react-datetime#326]
why is strictParsing not working? If I turn it to true, I can type in whatever numbers and alphabetical characters I want.

Codepen below for reference. Does anyone have any idea on how to fix this?

http://codepen.io/anon/pen/RVxdMx

**Comment by layneanderson** [comment]
Sorry, I'm not sure exactly what the issue is.  Can you provide more detail?  I would suggest following the issue template.

If I had to guess though I'd offer that moment's strictParsing requires a format to be specified.  Also, I don't believe using the strictParsing prop (react-datetime) restricts what is typed in the input (only what is accepted).
