### ISSUE TITLE
How Can I add a mask on this component?

### ISSUE THREAD

**Issue by webvini** [YouCanBookMe/react-datetime#397]
Hello everyone,

I need to create input (input-datetime component) but that it is capable of allow to add another component, ex: <InputMask....

Currently, we are useing datepicker component that allow to use a input custom.

Is it possible on this component?

Thank you so much, guys

**Comment by simeg** [comment]
Hey @webvini. I'm not sure what you mean by "add a mask". Could you explain in a different way or more in detail? Thanks.

**Comment by webvini** [comment]
Hi @simeg thank your feedback.

I mean, I would like to use Input Mask Component. For example: __/__/____ for adding 06/06/2017.

For this reason I need to insert a Input Custom.

Thank you so much

**Comment by simeg** [comment]
Hi @webvini.

I still don't fully understand what you want to do. But with this component you add some props to the input by using `inputProps` but you cannot fully customize the HTML input element. It's on our roadmap for the next major version though.

**Comment by webvini** [comment]
Hi @simeg 

Take a look this great component: http://sanniassin.github.io/react-input-mask/demo.html

I need some like this:

<Datetime
   timeFormat={false}
   inputCustom={ <InputMask mask="99/99/9999" placeholder="Enter birthdate" /> }
/>

But now I understand that it's not possible.
I am looking forward for this future feature.

Thank you so muck.

**Comment by DanZeuss** [comment]
Basically, is to maintain the mask while the user is typing.

If the user want to type (to speed up the process), the user would:

1. Have the input with a mask, like __/__/____;
2. Type, and when typing, it would maintain the mask, like:
- Final Date: 04/14/2017
- The user starts to type 0414;
- The component renders 04/14/____;

I'm looking for a solution for it too @webvini

**Comment by webvini** [comment]
Hello, @DanZeuss ,

Meanwhile I've added "readonly" on the Input, for solve my problem, in other words, the user can only select the Date on the "Modal". :(

Good luck

**Comment by lakshmikarnati** [comment]
Basically, is to maintain the mask while the user is typing.

If the user want to type (to speed up the process), the user would:

Have the input with a mask, like //____;
Type, and when typing, it would maintain the mask, like:
Final Date: 04/14/2017
The user starts to type 0414;
The component renders 04/14/____;
I'm looking for a solution for it too @webvini
I would like to add mask datetime component may i know the process.Please replay me

**Comment by rikkit** [comment]
@DanZeuss @webvini @lakshmikarnati create a new input with your input mask library, hide react-datetime's input field using CSS, and bind your new input's onChange handler to the value property of react-datetime. This doesn't need to be core functionality

**Comment by webvini** [comment]
Hi @rikkit 
It looks good.
I already solved this problem with readonly attribute, our consumer already approved this solution.

I hope this great feature is added soon on this DateTime component

thank you for your help

**Comment by lakshmikarnati** [comment]
Hi,
 may i know how do we use read-only property datetime control.

**Comment by simeg** [comment]
This could be fixed in our planned V3, where you would be able to input the entire `<input>` element for the component to use. We are not there yet though so right now this is not possible.

Will close this now, but let me know if you want to re-open it for further discussions.

@lakshmikarnati This is what you're looking for:
```js
inputProps={{ readOnly: true }}
```

**Comment by henriquealbertbill** [comment]
Hello, I know this discussion is old, but I came across this because I was also having the same problem and I managed to make a solution. I will share to help future people.

First I created a component for my DatePick and used the react-input-mask lib.

My component looks like this:
`import React from "react";
import ReactDatetime from "react-datetime";
import InputMask from "react-input-mask";
import {
Input
} from "reactstrap";


function MyDTPicker(props){
  const { value, onChange } = props;
  const renderInput = (props) => {
    return (
        <Input {...props}
        mask="99/99/9999"
        tag={InputMask}
        maskChar="_" />
    );
  }
    return (
    <ReactDatetime renderInput={renderInput} timeFormat={false} value={value == null ? '' : value} onChange={onChange}  />
    )
}

export default MyDTPicker;`

Now just import the component on your page and pass value and onChange like this:
`             
                  <MyDTPicker 
                  value={birthday}
                  onChange={(e) => setBirthday(e)}
                />`
