### ISSUE TITLE
peerDependencies error with react 0.13.x

### ISSUE THREAD

**Issue by markmus** [YouCanBookMe/react-datetime#42]
How I could fix this issue? I'm getting `peerDependencies` error when I try to update to 2.0.

Looks the problem is coming from `npm ERR! peerinvalid Peer react-dom@0.14.3 wants react@^0.14.3`.

Currently I'm using `"react": "^0.13.3"`
While I need to upgrade my `react-datetime` to 2.0 since I'm getting error of `OnClickOutside` in IE9 on my current `"react-datetime": "^1.3.0"`

**Comment by brenoferreira** [comment]
:+1: for this. Why not release a version with support for 0.14 only?

**Comment by arqex** [comment]
Hi

Yes, next version will be React 0.14 only compatible, having it compatible with previous versions is just too complicated.

Wait for news soon :)

**Comment by brenoferreira** [comment]
Great! But is there any reason for having the peerDependency for react-dom on this current release?

**Comment by simeg** [comment]
@brenoferreira from what I can find, the only explicit reference to `react-dom` in the code base is in the test file. From that information only I think it can be moved to `devDependencies`.

@arqex what is the plan with this? Should we aim for a release who fully supports React 0.14 (or even 0.15 maybe)? Also, do you think we can move the dependency `react-dom`? **Note**, I have not tried building the component without `react-dom`.

**Comment by bjbrewster** [comment]
Hello, I would like to get the ball rolling on v3 and bringing this project into 2017.  

Can I propose we set React peer dependency to 15+? 

I've forked the project and am currently rewriting src files in ES2015 and removing redundant dependencies.  I am using babel cli to convert the `/src` files to `/lib` files in plain js (as it is now). The `package.json` "main" entry would change from `/DateTime.js` to `/lib/DateTime.js` so it would behave the same as it is now, and a new `package.json` "module" entry could point to `/src/DateTime.js` which is used by Webpack and other bundlers looking for modern js.

To begin with, I will make sure the interface is exactly the same as it is now but with updating the major revision, now would be a good time to make a major change like removing `moment` as a core dependency.  [Fecha](https://www.npmjs.com/package/fecha) is made as a very lightweight (2k min gzipped) replacement for Moment and supports the same format strings.  I looked into [Date Fns](https://www.npmjs.com/package/date-fns) but it does not support parsing dates with a format string (only ISO 8601 formats).  We could also add params for formatDate, formatTime and parseDate to allow users to provide their own custom methods.  

Users would no longer be able to pass Moment objects as params to the component though.  They would need to call `.toDate()` on each Moment object when passing it in.  If needed we could create a wrapper for DateTime that does accept moment props and does the conversion before passing to DateTime.

Anyhow, I'm working on this now and would love for it to become part of v3 instead of leaving this in my own GitHub repo.

Cheers,
Brendan

**Comment by bjbrewster** [comment]
I have a work in progress v3 branch where I've refactored the src using ES6, removed lots of unused styles and fixed a few bugs.  There was lots of really bad code!  Anyhow, I'd appreciate some feedback and would like to discuss a few things.

I see someone updated the react-onclickoutside dependency to the latest ^6 version but it has peer deps of React 15.5.x+ or 16.0+ which is a problem unless we update this project's peer deps to the same.  For now, I've updated my v3 branch to use version's react-onclickoutside to the latest ^5 version that isn't as restrictive.

Is it intentional that the Date Picker Views are rendered even when the Picker is not "open"?  At the moment it's using a CSS class to hide/show the component which is not the React way and IMO really bad.  e.g. If you have a form with a list of 1000 items, each with their own DateTime input box, they will all have a rendered DateTime Picker view as well (just hidden using CSS). This is very inefficient. It should just not include the Picker view when not open.  I've made my v3 branch do this and updated many tests accordingly.  If the desire for it to be always open so users can add CSS transition animations, we add CSS classes for on enter and about to leave and delay the removal to allow for this.

The current TimeConstraints seem completely broken to me.  Why would you even want to restrict mins or seconds let alone hours with the same values for every day?  And a min/max mins or secs seems to only make sense as a whole min/max time (hours, mins and secs together), not separate as it is now.  A lot of people are complaining that this feature is completely useless and I can see why.  For now I've disabled custom time constraints in my v3 branch as the current feature is broken IMO.  A better solution would be a callback that is called with the selected day that returns an array of allowed min/max time ranges.  An example usage would be for a booking system where there are slots free at 8:30am to 10:15am and 3:45pm to 6:15pm.  I see someone is working on a better time input (like using an analogue clock) so I'll leave it to others to decide a better design. 

Anyhow, I've had fun refactoring this project and only have a bit more to do in the main DateTime class.  I've cleaned up a lot of the logic statements that will make it a lot more maintainable.  I tried using ES6 classes but found the intermediate libs and bundled packages were very bloated so I reverted to using create-react-class and was amazed at how much smaller it is.  My min bundle is about 30k compared to the current 40k. :-)

Feedback is welcome.  When I'm happy with it, I'll add a merge request.

**Comment by simeg** [comment]
@bjbrewster see #458 for bumping React peer dependency version.

**Comment by simeg** [comment]
See https://github.com/YouCanBookMe/react-datetime/pull/463.

**Comment by simeg** [comment]
Btw @bjbrewster, I haven't seen you here in a while. What happened to your ES2015 re-write? :) Sounds interesting.
