### ISSUE TITLE
Enhancements?

### ISSUE THREAD

**Issue by arqex** [YouCanBookMe/react-datetime#8]
Hi!

You might that react-datetime is still in process to be stable. It would be great to know developer's thoughts about the API.

From my point of view I have some doubts about the way of making it work as a datepicker/timepicker only. Currently if you pass prop `dateFormat` and not a `timeFormat` you only get the datepicker. The same happens in the other direction. But this way it is not possible to use the locale default format, so I was thinking about change it.

Also I was thinking about deprecating `minDate` and `maxDate` and creating a prop `validDate` that accepts a function to let the developer pick fine grained valid dates.

What do you think? Do you have other ideas or needs?

**Comment by aleemb** [comment]
`minDate` and `maxDate` have better UX in terms of API design and it is also 99% of your use-case. However, `validDate` and min/max are not mutually exclusive so I would propose having all three. `validDate` will help for the rare case where for example a user only wants weekdays to be selectable. However, I would rename that to `isValidDate` or `filterDate`. This will also help with backward compatibility (if that is a concern).

Similarly, for the date vs time issue, it might be better to setup boolean options such as 'enableDatePicker` and `enableTimePicker`, both of which can be `true` by default. And have a single field called `format` which makes sense since it will be bound to a single input box and it will be in line with the ISO datetime format as well as allowing you to pass through to `moments.js` without any string gymnastics.

On a related note, I came across http://jquense.github.io/react-widgets/docs/#/datetime-picker which is worth a look.

**Comment by anateus** [comment]
Agreed with @aleemb on the min/max API as well as enabling.

I previously used **react-widgets**, but have had compatibility issues, testing issues (hard to automate cucumber tests with how it's implemented in the DOM), and dependency breakages. One of the things I like is how compact and efficient **react-datetime** is. So I would look to it as inspiration for some features, but I'd be careful to maintain the lack of bloat.

The only immediate enhancement I need is compatibility down to IE9 (which I unfortunately have to support), but I'm about to put up a PR that enables that :) That's actually something that's a particular advantage of **react-datetime**, I tested several other datepickers and most of them made even IE11 very unhappy, and just didn't work in older ones. Making it work in older browsers was pretty easy.

**Comment by arqex** [comment]
Hey thanks guys!

Are you already using `minDate` `maxDate`? Is it some kind of standard? 

It happens that you have reached to this project in an alpha stage, it started as a fork of https://github.com/quri/react-bootstrap-datetimepicker, and after a huge cleanup I decide to have it as a completely different datepicker, but it still maintains part of its API and I don't like some of it.

I think of `validDate` (or filterDate) as a replacement for `minDate` and `maxDate`. It will make react-datetime smaller and ti will give more control to the developer. If your use case rendering valid dates between two given one you would do:

```js
function minMaxDate( currentDate ){
  return currentDate > minDate && currentDate < maxDate;
}
<Datetime validDate={ minMaxDate } />
```
The problem of having all of three `minDate`, `maxDate`, and `validDate` is that there might be some conflicts if they are used together. What if the user says that a date is valid but is previous to the `minDate`? That is a symptom of a bad designed API. Furthermore, having just one method makes the API smaller and I need less code to handle the feature internally, so it is easier to maintain.

@aleemb it is cool the idea of enabling toggles for the different pickers, but I still need to have the two different formats for date and time because, in a single format string for both, I can't guess what part is for the time and what for the date, so I couldn't render the headers for the calendar.

Maybe, if I rename `dateFormat` and `timeFormat` to `enableDate` and `enableTime`, and it accepts:

* true (default): Show the picker and use the default locale format
* String: Show the picker and use the format in the string.
* false: Don't show the picker.

That would be better....

Thoughts?

**Comment by anateus** [comment]
I do use `minDate`. For combining the three I think the logic should be: If you use `validDate` it should ignore anything that's in `minDate` and `maxDate`. I think the way to implement this is that it always execute `validDate`, but the default function for `validDate` acceses the `minDate` and `maxDate` props. This ensures there will never be an issue, because as soon as `validDate` is overriden the min/max props can be accessed (if the overriders desires) or ignored.

As far as the formats, although it would add a bunch to the API, I think have separate `date|timeFormat` and `enableDate|Time` props is more semantically clear. Having an `enableX` that actually takes a format string is a little confusing. I think the use case that's enabled by having these 4 props is if I want say... just date and no time, but I don't want to override the default formats.

**Comment by arqex** [comment]
Hey guys, thanks for your help.

After much thinking I have settle down the API to be stable, you can see it here:

https://github.com/arqex/react-datetime/tree/release-candidate.

Finally I have removed the `minDate` and `maxDate`, I'm sorry because I know you were using them, but their functionality is very limited and overlaped the one of the needed `isValidDate` prop.

As for enabling pickers, I have decided that they need to be enabled by default. If you want to disable them it is possible to set `dateFormat` and `timeFormat` to `false`.

There are more functionalities and breaking changes in the release candidate:
https://github.com/arqex/react-datetime/blob/release-candidate/CHANGELOG.md

I hope you like it.

**Comment by code4aman** [comment]
Hi! Can you add TypeScript definition file?

**Comment by arqex** [comment]
Sure, but I have no idea about typescript. If you create it and make a PR I will be glad to merge it.

**Comment by piotrblasiak** [comment]
How about making the component use inline styles?

**Comment by arqex** [comment]
Hey this issue it's so down on the list that it's not visible anylonger in the first page. Since all the suggestions have been included, I am closing this.
